language: node_js
node_js:
  - '8'

  # safelist
branches:
  only:
  - master
  - stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- "$@"
  - export PATH="$HOME/.yarn/bin:$PATH"